### PR TITLE
Icon Changes

### PR DESCRIPTION
**Pull request by Subaharish**
Signed-off-by: Subaharish <48942935+Subaharish@users.noreply.github.com>

### CODE REVIEW

**Comment by Subaharish** [comment]
@aravindvnair99 Don't merge this PR yet, Yash will tell you when to merge.

**Comment by newb-dev-1008** [comment]
@aravindvnair99 you can merge now, I have signed the MoU. Thank you so much for your help @Subaharish !

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Subaharish Please resolve the conflicts. You previous PR has been merged

**Comment by Subaharish** [comment]
> @Subaharish Please resolve the conflicts. You previous PR has been merged

@aravindvnair99  Conflicts are resolved.

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Subaharish Okay, that was quick. 😂 Have a look at the issues pointed out by @Code-factor as well.

**Comment by Subaharish** [comment]
> @Subaharish Okay, that was quick. 😂 Have a look at the issues pointed out by @code-factor as well.

@aravindvnair99  I didn't see that, my bad. Now its done.

**Review by aravindvnair99 — APPROVED** [review]

**Pull request merged**
