### PR TITLE
Theme fix

### LINKED ISSUE #4: Change the themes
Replace "The Theme" with "Tracks".

Tracks:
1. Crisis Response
2. Fintech
3. Healthcare
4. Cyber Security
5. Open Innovation

https://drive.google.com/drive/folders/1NX47QDPhYHkUhENXMM1WKnBTwPKDBfwx?usp=sharing

This folder contains all the required pictures for each track.

### PR DESCRIPTION
**Pull request by Subaharish**
Fixes #4 
-Added content under the title Track

### CODE REVIEW

**Comment by newb-dev-1008** [comment]
@aravindvnair99 please do merge this pull request.

**Comment by Subaharish** [comment]
@newb-dev-1008 @aravindvnair99 Replaced Ticket card with "Stay Tuned
Registration Starts soon!"

**Comment by newb-dev-1008** [comment]
@aravindvnair99 please merge this pull request

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Subaharish Please resolve the conflicts. Moving this to draft for now.

**Comment by Subaharish** [comment]
@aravindvnair99 I don't have access to resolve the conflicts.

**Comment by Subaharish** [comment]
> @Subaharish Please resolve the conflicts. Moving this to draft for now.

@aravindvnair99 I don't have access to resolve the conflicts.

**Comment by Subaharish** [comment]
Don't merge this one. Merge the 'Bug Fixes' PR. Added all the required changes there.

**Pull request closed without merging**
